name: assets_builder
description:  assets资源路径映射
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #  flutter:
  #    sdk: flutter
  dart_style: ^1.2.7
  code_builder: ^3.2.0
  yaml: ^2.1.16

dev_dependencies:
#  flutter_test:
#    sdk: flutter




